[workspace]
members = [
    "crates/shell-core",
    "crates/shell-platform",
    "crates/shell-hyprland",
    "crates/shell-linux",
    "crates/shell-config",
    "crates/shell-theme",
    "crates/shell-ui-gpui",
    "crates/shell-app",
    "crates/modules/*",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
publish = false

[workspace.dependencies]
shell-core = { path = "crates/shell-core" }
shell-platform = { path = "crates/shell-platform" }
shell-hyprland = { path = "crates/shell-hyprland" }
shell-linux = { path = "crates/shell-linux" }
shell-config = { path = "crates/shell-config" }
shell-theme = { path = "crates/shell-theme" }
shell-ui-gpui = { path = "crates/shell-ui-gpui" }
luna-module-launcher = { path = "crates/modules/launcher" }
luna-module-calendar = { path = "crates/modules/calendar" }
luna-module-player = { path = "crates/modules/player" }
luna-module-theme = { path = "crates/modules/theme" }
luna-module-resources = { path = "crates/modules/resources" }
luna-module-clock = { path = "crates/modules/clock" }
luna-module-settings = { path = "crates/modules/settings" }

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
chrono = "0.4.45"
serde = { version = "1.0.229", features = ["derive"] }
toml = "0.8.23"
arc-swap = "1.7.1"
notify = "8.2.0"
notify-debouncer-full = "0.7.0"
serde_json = "1.0.151"
gpui-kit = "0.6"
gpui = { git = "https://github.com/zed-industries/zed", rev = "a9cdfc9936c4ccf0503ee4631204e045f913e2c1", package = "gpui", default-features = false, features = ["wayland"] }
gpui-platform = { git = "https://github.com/zed-industries/zed", rev = "a9cdfc9936c4ccf0503ee4631204e045f913e2c1", package = "gpui_platform", default-features = false, features = ["wayland"] }
tempfile = "3"
wayland-client = "0.31.15"
wayland-protocols-wlr = { version = "0.3.9", features = ["client"] }
