[package]
name = "shell-app"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
shell-config.workspace = true
shell-core.workspace = true
shell-hyprland.workspace = true
shell-linux.workspace = true
shell-platform.workspace = true
shell-theme.workspace = true
shell-ui-gpui.workspace = true
luna-module-launcher.workspace = true
luna-module-calendar.workspace = true
luna-module-player.workspace = true
luna-module-theme.workspace = true
luna-module-resources.workspace = true
luna-module-clock.workspace = true
luna-module-settings.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
